<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>velma</string>
	</array>
	<key>name</key>
	<string>VELMA</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(?i)(@|(\((?=R[0-7]\))))(R[0-7])(\))?</string>
			<key>name</key>
			<string>entity.name.tag.contents.velma</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i)(R[0-7])\b</string>
			<key>name</key>
			<string>variable.parameter.register.velma</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[0-7]+\b</string>
			<key>name</key>
			<string>variable.parameter.memory.velma</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(\.ORG|\.WORD|\.BLK|ADD(#)?|SUB|MUL|DIV|CMP|TST|BIT|MOV(#|@)?|(@)?MOV|ASHR|LSHR|LSHL|CLR|INC|DEC|BIC|BIS|BIF|JUMP(@)?|JSR|RTS|RTI|BR|BNE|BEQ|BGE|BLT|BVC|BVS|BCC|BCS|BGT|BLE|HALT|NOP)(?!\w+)(?!\w*:)</string>
			<key>name</key>
			<string>keyword.control.velma</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\s)*;.*$</string>
			<key>name</key>
			<string>comment.velma</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#[0-7]+\b</string>
			<key>name</key>
			<string>constant.numeric.octal.velma</string>
		</dict>
		<dict>
			<key>match</key>
			<string>("|').*?("|')</string>
			<key>name</key>
			<string>string.velma</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\w+(?=:)</string>
			<key>name</key>
			<string>entity.name.function.velma</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=(B(NE|EQ|GE|LT|VC|VS|CC|CS|GT|LE))|JSR)\s+(\w+)</string>
			<key>name</key>
			<string>entity.name.function.velma</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=BR)\s+(\w+)</string>
			<key>name</key>
			<string>entity.name.function.velma</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=JUMP)\s+(\w+)</string>
			<key>name</key>
			<string>entity.name.function.velma</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.velma</string>
	<key>uuid</key>
	<string>80bee9e8-acd5-44ac-b7b2-6cae65dac594</string>
</dict>
</plist>
